### ISSUE TITLE
About FaceSEIP Dataset

### ISSUE THREAD

**Issue by LiquidAmmonia** [CrisHY1995/headnerf#12]
Hi, great work and congrats on your cvpr acceptance. 

I'am interested in the FaceSEIP Dataset mentioned in your paper. However, I failed to find any description or reference about this dataset. Did you collect this dataset? Would you make it publicly available? 

Thank you for your time.

**Comment by CrisHY1995** [comment]
Thanks for your interest in our work. 

We purchased faceSEIP dataset through DATATANG (https://m.datatang.ai/datasets/4). 
Then we perform the post-process to filter out invalid data and generate the corresponding 3DMM parameters of the rest.

Best,
Yang.
