### ISSUE TITLE
Result of fitting image

### ISSUE THREAD

**Issue by Jio0728** [CrisHY1995/headnerf#2]
Hello! Thank you for your great work. It is definitely what I needed.

As I test the model with my own dataset, it turned out that the fitting is not done well.
I attached the result image here.

I exactly followed the guideline introduced on readme, and it worked really fine with the test images.

Could you please give us some advice on testing the model with own datasets?

![KakaoTalk_20220501_010413317](https://user-images.githubusercontent.com/87808237/166113680-58e9a713-ed19-47d7-ab7a-f60224825a7f.png)

**Comment by Jio0728** [comment]
Oh I found that it was the problem of preprocessing.
I cropped the image to be 1024*1024 and resized it to be 512*512 and it solved the problem!

**Comment by zhanglonghao1992** [comment]
@Jio0728  
Same problem. How can you fix that. Do we need to crop the image to keep only the head？ Do we need the image to be square instead of rectangular?

**Comment by Jio0728** [comment]
The above picture was the result of fitting with the "resized" image. The aspect ratio of the image changed during the image resizing process. You can check the change of the ratio from the input picture above. It is compressed vertically. We solved the problem by just "cropping" the image. Without change of the aspect ratio, we cropped the image to maintain 512*512 size or 256*256 size and it worked well.
